# Generated by Django 5.1 on 2024-09-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('unnamed_0', models.BigIntegerField(blank=True, db_column='Unnamed: 0', null=True)),
                ('vintage_id', models.BigIntegerField(db_column='Vintage_Id', primary_key=True, serialize=False)),
                ('vintage_name', models.TextField(blank=True, db_column='Vintage_Name', null=True)),
                ('wine_id', models.BigIntegerField(blank=True, db_column='Wine_Id', null=True)),
                ('wine_name', models.TextField(blank=True, db_column='Wine_Name', null=True)),
                ('wine_name_kor', models.TextField(blank=True, db_column='Wine_Name_Kor', null=True)),
                ('year', models.TextField(blank=True, db_column='Year', null=True)),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
                ('ratings_count', models.BigIntegerField(blank=True, db_column='Ratings_Count', null=True)),
                ('ratings_average', models.FloatField(blank=True, db_column='Ratings_Average', null=True)),
                ('type_id', models.BigIntegerField(blank=True, db_column='Type_Id', null=True)),
                ('is_natural', models.BigIntegerField(blank=True, null=True)),
                ('body', models.BigIntegerField(blank=True, db_column='Body', null=True)),
                ('acidity', models.FloatField(blank=True, db_column='Acidity', null=True)),
                ('intensity', models.FloatField(blank=True, db_column='Intensity', null=True)),
                ('sweetness', models.FloatField(blank=True, db_column='Sweetness', null=True)),
                ('tannin', models.FloatField(blank=True, db_column='Tannin', null=True)),
                ('flavor', models.TextField(blank=True, db_column='Flavor', null=True)),
                ('alcohol', models.FloatField(blank=True, db_column='Alcohol', null=True)),
                ('volume', models.BigIntegerField(blank=True, db_column='Volume', null=True)),
                ('food', models.TextField(blank=True, db_column='Food', null=True)),
                ('grape', models.TextField(blank=True, db_column='Grape', null=True)),
                ('region_name', models.TextField(blank=True, db_column='Region_Name', null=True)),
                ('region_id', models.BigIntegerField(blank=True, db_column='Region_Id', null=True)),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('winery_id', models.BigIntegerField(blank=True, db_column='Winery_Id', null=True)),
                ('winery_name', models.TextField(blank=True, db_column='Winery_Name', null=True)),
                ('price_usd', models.FloatField(blank=True, db_column='Price_USD', null=True)),
                ('price_kor', models.BigIntegerField(blank=True, db_column='Price_KOR', null=True)),
                ('currency', models.TextField(blank=True, db_column='Currency', null=True)),
                ('bottle_medium', models.TextField(blank=True, null=True)),
                ('bottle_small', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
    ]
